version: "3.9"

services:

  app:
    container_name: bakai-smart-search
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8033:8000"
    depends_on:
      - db
      - redis
      - kafka
      - celery
      - zookeeper

    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/smart_search
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"

  celery:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: bakai-smart-search-celery
    command: 'celery -A src.worker.main:celery worker -Q nightly_task --loglevel=INFO --beat'
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smart_search
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
#      - "9092:9092"

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.152.93.7:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    hostname: kafka
