version: "3.9"

services:
  app:
    image: IMAGE_NAME  
    container_name: bakai-smart-search-preprod
    restart: always
    env_file:
      ./.env
    networks:
      - smart-search_network
    ports:
      - "8001:8000"
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"

  celery:
    container_name: bakai-smart-search-celery-preprod
    image: IMAGE_NAME
    command: 'celery -A src.worker.main:celery worker -Q nightly_task --loglevel=INFO --beat'
    env_file:
      ./.env
    networks:
      - smart-search_network

networks:
  smart-search_network:

